name: Playwright Tests on Azure VM

on:
  push:
    branches: [ "tests", "main" ]
  pull_request:
    branches: [ "tests", "main" ]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "TARGET_VM_URL=http://${{ secrets.TARGET_VM_IP }}" > .env

    - name: Run Playwright tests
      run: npx playwright test
